apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-set
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/phoenix0xff/GitOps.git
        revision: HEAD
        directories:
          - path: manifest/*
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
      annotations:
        notifications.argoproj.io/subscribe.dora-on-deployed: dora-collector
    spec:
      project: default
      source:
        repoURL: https://github.com/phoenix0xff/GitOps.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
