apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app1
  template:
    metadata:
      labels:
        app: node-app1
      annotations:
        org.opencontainers.image.revision: 4ff3ed3186f14aa4ec368d635e0a3e69053ee8eb
    spec:
      containers:
        - name: node-app1
          image: ens19kav/my-app1:main-99
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
