apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app1-deployment
  annotations:
    dora.dev/source-commit: b7857a6551bbe2a33c62a1b3904f6e427c6ccf4e
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app1
  template:
    metadata:
      labels:
        app: node-app1
      annotations:
        org.opencontainers.image.revision: b7857a6551bbe2a33c62a1b3904f6e427c6ccf4e
    spec:
      containers:
        - name: node-app1
          image: ens19kav/my-app:b7857a6551bbe2a33c62a1b3904f6e427c6ccf4e
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
