apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app1
  template:
    metadata:
      labels:
        app: node-app1
      annotations:
        org.opencontainers.image.revision: 17d61e461c6d7b3c41b87a08aebb38d21fe228c8
        sim-readiness-run: "20251202130815"
    spec:
      containers:
        - name: node-app1
          image: ens19kav/my-app1:main-53
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /nonexistent-health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
