apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app1
  template:
    metadata:
      labels:
        app: node-app1
      annotations:
        org.opencontainers.image.revision: dd5513111fd500725cfb90c0f95c6b0de9ee30da
    spec:
      containers:
        - name: node-app1
          image: ens19kav/my-app1:main-111
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
