apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app1-deployment
  annotations:
    dora.dev/source-commit: ec57311d6d5026f9bd407221c8463f4ea34226b7
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app1
  template:
    metadata:
      labels:
        app: node-app1
      annotations:
        org.opencontainers.image.revision: ec57311d6d5026f9bd407221c8463f4ea34226b7
    spec:
      containers:
        - name: node-app1
          image: ens19kav/my-app:main-10
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
