apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app1-deployment
  annotations:
    dora.dev/source-commit: 90768c0bc2e7a5e529666179de7d9a9656266784
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app1
  template:
    metadata:
      labels:
        app: node-app1
      annotations:
        org.opencontainers.image.revision: 90768c0bc2e7a5e529666179de7d9a9656266784
    spec:
      containers:
        - name: node-app1
          image: ens19kav/my-app:90768c0bc2e7a5e529666179de7d9a9656266784
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
