apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app1-deployment
  annotations:
    dora.dev/source-commit: dae32a5458751a9f2612cb51bf7dcf3e4a8e82b1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app1
  template:
    metadata:
      labels:
        app: node-app1
      annotations:
        org.opencontainers.image.revision: dae32a5458751a9f2612cb51bf7dcf3e4a8e82b1
    spec:
      containers:
        - name: node-app1
          image: ens19kav/my-app:dae32a5458751a9f2612cb51bf7dcf3e4a8e82b1
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
