apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app1
  template:
    metadata:
      labels:
        app: node-app1
      annotations:
        org.opencontainers.image.revision: 9421c586488b550c5322e018b977c46a223c764f
    spec:
      containers:
        - name: node-app1
          image: ens19kav/my-app1:main-68
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
