apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app1-deployment
  annotations:
    dora.dev/source-commit: 71632f11f1ec06cb257f6860635a323da079f464
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app1
  template:
    metadata:
      labels:
        app: node-app1
      annotations:
        org.opencontainers.image.revision: 71632f11f1ec06cb257f6860635a323da079f464
    spec:
      containers:
        - name: node-app1
          image: ens19kav/my-app:71632f11f1ec06cb257f6860635a323da079f464
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
