apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app1-deployment
  annotations:
    dora.dev/source-commit: c23ca69b362d215904944374754e5c265dfd01d0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app1
  template:
    metadata:
      labels:
        app: node-app1
      annotations:
        org.opencontainers.image.revision: c23ca69b362d215904944374754e5c265dfd01d0
        sim-crashloop-run: "20251103195752"
    spec:
      containers:
        - name: node-app1
          image: ens19kav/my-app:c23ca69b362d215904944374754e5c265dfd01d0
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          command:
            - /bin/sh
            - -c
          args:
            - echo Simulated CrashLoop; exit 1
