apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app1-deployment
  annotations:
    dora.dev/source-commit: a1032c15228e05883b3aafae0fdefd30b6d03cd5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app1
  template:
    metadata:
      labels:
        app: node-app1
      annotations:
        org.opencontainers.image.revision: a1032c15228e05883b3aafae0fdefd30b6d03cd5
    spec:
      containers:
        - name: node-app1
          image: ens19kav/my-app:main-12
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
