apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app1
  template:
    metadata:
      labels:
        app: node-app1
      annotations:
        org.opencontainers.image.revision: 6f9fd8007c4ee1a2b4d1e74ef0c60e411bb7dd8b
    spec:
      containers:
        - name: node-app1
          image: ens19kav/my-app1:main-113
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
