apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app1
  template:
    metadata:
      labels:
        app: node-app1
      annotations:
        org.opencontainers.image.revision: 17c966c8bf4da4141eca55f3cb25f798fac62526
    spec:
      containers:
        - name: node-app1
          image: ens19kav/my-app1:main-17
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
