apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app1-deployment
  annotations:
    dora.dev/source-commit: 5a576ebbcd7869e51025bc13bd4b58c18065d0c3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app1
  template:
    metadata:
      labels:
        app: node-app1
      annotations:
        org.opencontainers.image.revision: 5a576ebbcd7869e51025bc13bd4b58c18065d0c3
    spec:
      containers:
        - name: node-app1
          image: ens19kav/my-app:5a576ebbcd7869e51025bc13bd4b58c18065d0c3
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
