apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app1-deployment
  annotations:
    dora.dev/source-commit: 2bbc91bf62a3cd01acf28ecbf9c86585428b595d
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app1
  template:
    metadata:
      labels:
        app: node-app1
      annotations:
        org.opencontainers.image.revision: 2bbc91bf62a3cd01acf28ecbf9c86585428b595d
    spec:
      containers:
        - name: node-app1
          image: ens19kav/my-app:main-11
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
