apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app1-deployment
  annotations:
    dora.dev/source-commit: fefcd90fd60148940bc6c5fc79939783fb1a23e1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app1
  template:
    metadata:
      labels:
        app: node-app1
      annotations:
        org.opencontainers.image.revision: fefcd90fd60148940bc6c5fc79939783fb1a23e1
    spec:
      containers:
        - name: node-app1
          image: ens19kav/my-app:fefcd90fd60148940bc6c5fc79939783fb1a23e1
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
