apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app1
  template:
    metadata:
      labels:
        app: node-app1
      annotations:
        org.opencontainers.image.revision: 582b3a122b06b71b01588347ca151f037a96b98b
        sim-readiness-run: "20251207145859"
    spec:
      containers:
        - name: node-app1
          image: ens19kav/my-app1:main-95
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /nonexistent-health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
