apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app3-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app3
  template:
    metadata:
      labels:
        app: node-app3
      annotations:
        org.opencontainers.image.revision: 2501af49f7f6433ef022401de7acd762da03e4ff
        sim-readiness-run: "20251207165234"
    spec:
      containers:
        - name: node-app3
          image: ens19kav/my-app3:main-15
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /nonexistent-health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
