apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app3-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app3
  template:
    metadata:
      labels:
        app: node-app3
      annotations:
        org.opencontainers.image.revision: 4036ef876529716d58c12042b097e5a7ad335caa
    spec:
      containers:
        - name: node-app3
          image: ens19kav/my-app3:main-2
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
