apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app3-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app3
  template:
    metadata:
      labels:
        app: node-app3
      annotations:
        org.opencontainers.image.revision: 487c3eb922d18cf1aaa1ddca189f6d206e474627
    spec:
      containers:
        - name: node-app3
          image: ens19kav/my-app3:main-32
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
