apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app3-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app3
  template:
    metadata:
      labels:
        app: node-app3
      annotations:
        org.opencontainers.image.revision: 5606a4510a0c0db1545ed47b3246b3e987d74e7e
    spec:
      containers:
        - name: node-app3
          image: ens19kav/my-app3:main-19
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
