apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app2-deployment
  annotations:
    dora.dev/source-commit: 62b1e43b564d43ac8f07ecefd5f6d5920dec7f7d
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app2
  template:
    metadata:
      labels:
        app: node-app2
      annotations:
        org.opencontainers.image.revision: 62b1e43b564d43ac8f07ecefd5f6d5920dec7f7d
    spec:
      containers:
        - name: node-app2
          image: ens19kav/my-app2:62b1e43b564d43ac8f07ecefd5f6d5920dec7f7d
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
