apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app2-deployment
  annotations:
    dora.dev/source-commit: 1d09b1ecab1fd56f9e1d8e7673981169f5c017e5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app2
  template:
    metadata:
      labels:
        app: node-app2
      annotations:
        org.opencontainers.image.revision: 1d09b1ecab1fd56f9e1d8e7673981169f5c017e5
    spec:
      containers:
        - name: node-app2
          image: ens19kav/my-app2:1d09b1ecab1fd56f9e1d8e7673981169f5c017e5
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
