apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app2-deployment
  annotations:
    dora.dev/source-commit: 05e108c6e6931a8c63b523a580f482ff5fc98b52
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app2
  template:
    metadata:
      labels:
        app: node-app2
      annotations:
        org.opencontainers.image.revision: 05e108c6e6931a8c63b523a580f482ff5fc98b52
    spec:
      containers:
        - name: node-app2
          image: ens19kav/my-app2:05e108c6e6931a8c63b523a580f482ff5fc98b52
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
