apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app2-deployment
  annotations:
    dora.dev/source-commit: 4d21631acad79c7ea2d7ad1634edb81f8c02ccc8
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app2
  template:
    metadata:
      labels:
        app: node-app2
      annotations:
        org.opencontainers.image.revision: 4d21631acad79c7ea2d7ad1634edb81f8c02ccc8
    spec:
      containers:
        - name: node-app2
          image: ens19kav/my-app2:4d21631acad79c7ea2d7ad1634edb81f8c02ccc8
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
