apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app2-deployment
  annotations:
    dora.dev/source-commit: 31c112389ae1fcee92ca2ae3bdbe4d54cd8fdeb9
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app2
  template:
    metadata:
      labels:
        app: node-app2
      annotations:
        org.opencontainers.image.revision: 31c112389ae1fcee92ca2ae3bdbe4d54cd8fdeb9
    spec:
      containers:
        - name: node-app2
          image: ens19kav/my-app2:31c112389ae1fcee92ca2ae3bdbe4d54cd8fdeb9
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
