apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app2
  template:
    metadata:
      labels:
        app: node-app2
      annotations:
        org.opencontainers.image.revision: fa3f66b6e6a42aacd8a66a386979b8c35620db1a
        sim-readiness-run: "20251207154603"
    spec:
      containers:
        - name: node-app2
          image: ens19kav/my-app2:main-36
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /nonexistent-health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
