apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app2
  template:
    metadata:
      labels:
        app: node-app2
      annotations:
        org.opencontainers.image.revision: ae43cc3451c10de99d346ea06dcec2adce9888b6
    spec:
      containers:
        - name: node-app2
          image: ens19kav/my-app2:main-52
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
