apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app2
  template:
    metadata:
      labels:
        app: node-app2
      annotations:
        org.opencontainers.image.revision: 23de7ba822a541f8e6135d929800fcc0bd7f482d
    spec:
      containers:
        - name: node-app2
          image: ens19kav/my-app2:main-28
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
