apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app2-deployment
  annotations:
    dora.dev/source-commit: e2f85d4a53da84e094844ac7850cc9999ea04e67
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app2
  template:
    metadata:
      labels:
        app: node-app2
      annotations:
        org.opencontainers.image.revision: e2f85d4a53da84e094844ac7850cc9999ea04e67
    spec:
      containers:
        - name: node-app2
          image: ens19kav/my-app2:e2f85d4a53da84e094844ac7850cc9999ea04e67
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
